begin;
do $$
declare hid uuid; a uuid; b uuid; private_id uuid:=gen_random_uuid(); chore uuid:=gen_random_uuid(); expense uuid:=gen_random_uuid(); token uuid:=gen_random_uuid(); mutation uuid:=gen_random_uuid(); result jsonb; original jsonb; payload jsonb; coverage uuid; cursor text; count_rows integer:=0; shopping uuid:=gen_random_uuid(); copy1 uuid:=gen_random_uuid(); copy2 uuid:=gen_random_uuid(); receipt uuid; agreement uuid; today date:=(now() at time zone 'America/New_York')::date;
begin
 select household_id into hid from public.shared_home_config;
 select user_id into a from public.members where household_id=hid and name='Amane';
 select user_id into b from public.members where household_id=hid and name='Barnatt';
 perform public.shared_improvements('test-gateway','save_household',jsonb_build_object('actor',a,'settings',jsonb_build_object('timezone','America/Los_Angeles','quiet_start','23:00','quiet_end','07:00','templates','[]'::jsonb)));
 perform public.shared_improvements('test-gateway','save_reminders',jsonb_build_object('actor',a,'settings',jsonb_build_object('morning','09:17','evening',null,'topics',jsonb_build_array('chores','expenses'))));
 if public.shared_improvements('test-gateway','get',jsonb_build_object('actor',a))->'reminders'->>'morning'<>'09:17' then raise exception 'Reminder settings lost'; end if;
 begin perform public.shared_improvements('bad-gateway','get','{}'); raise exception 'Bad gateway allowed' using errcode='P0002'; exception when insufficient_privilege then null; end;
 payload:=jsonb_build_object('actor',a,'kind','task','title','My private errand','category','Personal','visibility','private','client_ids',jsonb_build_array(private_id),'mutation_id',mutation);
 result:=public.shared_home('test-gateway','create',payload);
 original:=public.shared_home('test-gateway','create',payload);
 if result<>original or (select count(*) from public.entries where id=private_id)<>1 then raise exception 'Offline replay duplicated'; end if;
 if exists(select 1 from jsonb_array_elements(public.shared_home('test-gateway','get',jsonb_build_object('actor',b))->'entries') e where e->>'id'=private_id::text) then raise exception 'Private item leaked to housemate'; end if;
 if exists(select 1 from jsonb_array_elements(public.shared_home('test-gateway','get','{}')->'entries') e where e->>'id'=private_id::text) then raise exception 'Private item leaked to shared screen'; end if;
 perform public.shared_home('test-gateway','update',jsonb_build_object('actor',a,'id',private_id,'done',true));
 if exists(select 1 from public.house_activity where household_id=hid and title='My private errand') then raise exception 'Private activity leaked'; end if;
 begin perform public.shared_home('test-gateway','update',jsonb_build_object('actor',b,'id',private_id,'done',false)); raise exception 'Private write allowed' using errcode='P0002'; exception when raise_exception then null; end;
 if jsonb_array_length(public.shared_improvements('test-gateway','search',jsonb_build_object('actor',b,'query','private errand'))->'results')<>0 then raise exception 'Search leaked private item'; end if;
 result:=public.shared_home('test-gateway','create',jsonb_build_object('actor',a,'kind','task','title','Clean kitchen','category','Chore','date',today,'assignee',a,'client_ids',jsonb_build_array(chore),'checklist',jsonb_build_array(jsonb_build_object('id','step','title','Wash dishes','done',false)),'effort_minutes',30));
 perform public.shared_home('test-gateway','update',jsonb_build_object('actor',a,'id',chore,'undo_token',token,'effort_minutes',45,'checklist',jsonb_build_array(jsonb_build_object('id','step','title','Wash dishes','done',true))));
 perform public.shared_home('test-gateway','undo_edit',jsonb_build_object('actor',a,'undo_token',token));
 if (select effort_minutes from public.entries where id=chore)<>30 or (select checklist->0->>'done' from public.entries where id=chore)<>'false' then raise exception 'Checklist undo lost metadata'; end if;
 perform public.shared_home('test-gateway','create',jsonb_build_object('actor',a,'kind','event','title','Away','category','Away','date',today,'assignee',a));
 result:=public.shared_improvements('test-gateway','request_coverage',jsonb_build_object('actor',a,'entry_id',chore,'candidate',b)); coverage:=(result->'coverage'->>'id')::uuid;
 if (select assignee from public.entries where id=chore)<>a then raise exception 'Assignment changed before approval'; end if;
 begin perform public.shared_improvements('test-gateway','decide_coverage',jsonb_build_object('actor',a,'id',coverage,'approve',true)); raise exception 'Self approval allowed' using errcode='P0002'; exception when raise_exception then null; end;
 perform public.shared_improvements('test-gateway','decide_coverage',jsonb_build_object('actor',b,'id',coverage,'approve',true));
 if (select assignee from public.entries where id=chore)<>b then raise exception 'Approval did not assign coverage'; end if;
 payload:=jsonb_build_object('actor',a,'id',expense,'kind','expense','title','Groceries','date',today,'amount_cents',101,'paid_by',a,'shares',case when a::text<b::text then jsonb_build_object(a,51,b,50) else jsonb_build_object(a,50,b,51) end,'recipient',null,'category','Groceries','percentages',jsonb_build_object(a,'50',b,'50'));
 perform public.shared_expenses('test-gateway','create',payload);
 token:=gen_random_uuid(); perform public.shared_expenses('test-gateway','update',payload||jsonb_build_object('category','Household','undo_token',token));
 perform public.shared_expenses('test-gateway','undo_edit',jsonb_build_object('actor',a,'undo_token',token));
 if (select category from public.household_expenses where id=expense)<>'Groceries' then raise exception 'Category undo failed'; end if;
 begin perform public.shared_expenses('test-gateway','update',payload||jsonb_build_object('percentages',jsonb_build_object(a,'60',b,'60'))); raise exception 'Invalid percentage allowed' using errcode='P0002'; exception when raise_exception then null; end;
 insert into public.household_expenses(id,household_id,kind,title,date,amount_cents,paid_by,shares,created_by) select gen_random_uuid(),hid,'expense','History '||g,today,100,a,jsonb_build_object(a,100),a from generate_series(1,121) g;
 loop
   result:=public.shared_expenses('test-gateway','get',jsonb_build_object('cursor',cursor));
   if jsonb_array_length(result->'expenses')>50 then raise exception 'Unbounded expense page'; end if;
   count_rows:=count_rows+jsonb_array_length(result->'expenses'); cursor:=result->>'next_cursor'; exit when cursor is null;
 end loop;
 if count_rows<122 then raise exception 'Expense pagination lost records'; end if;
 if not (result ? 'balances' and result ? 'summaries') then raise exception 'Full-ledger aggregates missing'; end if;
 result:=public.shared_household_life('test-gateway','get',jsonb_build_object('actor',a));
 if (select sum((r->>'amount_cents')::bigint) from jsonb_array_elements(result->'spending') r)<12201 then raise exception 'Household budget omitted older expense pages'; end if;

 perform public.shared_home('test-gateway','create',jsonb_build_object('actor',a,'kind','request','title','Breakfast: Milk, Eggs','category','Need','quantity',2,'unit','packs','store','Corner shop','client_ids',jsonb_build_array(shopping)));
 payload:=jsonb_build_object('actor',a,'id',shopping,'client_ids',jsonb_build_array(copy1,copy2),'mutation_id',gen_random_uuid());
 result:=public.shared_home('test-gateway','split_shopping',payload);
 perform public.shared_home('test-gateway','split_shopping',payload);
 if jsonb_array_length(result->'entries')<>2 or exists(select 1 from public.entries where id=shopping) or (select count(*) from public.entries where id in(copy1,copy2))<>2 then raise exception 'Shopping split was not atomic or replay-safe'; end if;
 if (select store from public.entries where id=copy1)<>'Corner shop' or (select amount from public.entries where id=copy1) is not null then raise exception 'Split lost store or invented a price'; end if;
 result:=public.shared_improvements('test-gateway','attach_receipt',jsonb_build_object('actor',a,'expense_id',expense,'storage_path',hid::text||'/'||expense::text||'/receipt.pdf','file_name','receipt.pdf','content_type','application/pdf','size_bytes',100));
 receipt:=(result->'file'->>'id')::uuid;
 if public.shared_improvements('test-gateway','receipt_file',jsonb_build_object('id',receipt))->'file'->>'file_name'<>'receipt.pdf' then raise exception 'Receipt unavailable'; end if;
 begin perform public.shared_improvements('test-gateway','attach_receipt',jsonb_build_object('actor',a,'expense_id',expense,'storage_path','another-house/receipt.pdf','file_name','receipt.pdf','content_type','application/pdf','size_bytes',100)); raise exception 'Invalid receipt path accepted' using errcode='P0002'; exception when raise_exception then null; end;
 perform public.shared_improvements('test-gateway','remove_receipt',jsonb_build_object('actor',a,'id',receipt));
 if exists(select 1 from public.expense_receipts where id=receipt) then raise exception 'Receipt removal failed'; end if;
 payload:=jsonb_build_object('edition','morning','date',today,'endpoint_hash',repeat('a',64));
 result:=public.shared_improvements('test-gateway','claim_delivery',payload);
 if not (result->>'claimed')::boolean then raise exception 'Initial reminder claim failed'; end if;
 if (public.shared_improvements('test-gateway','claim_delivery',payload)->>'claimed')::boolean then raise exception 'Concurrent reminder claim allowed'; end if;
 perform public.shared_improvements('test-gateway','finish_delivery',payload||jsonb_build_object('status','failed'));
 if not (public.shared_improvements('test-gateway','claim_delivery',payload)->>'claimed')::boolean then raise exception 'Failed reminder could not retry'; end if;
 perform public.shared_improvements('test-gateway','finish_delivery',payload||jsonb_build_object('status','sent'));
 if (public.shared_improvements('test-gateway','claim_delivery',payload)->>'claimed')::boolean then raise exception 'Delivered reminder resent'; end if;
 if public.shared_household_ops('test-gateway','status','{}')->>'schema_version'<>'026' then raise exception 'Schema status outdated'; end if;
 insert into public.agreements(household_id,slug,title) values(hid,'house','House history fixture') on conflict(household_id,slug) do update set title=excluded.title returning id into agreement;
 insert into public.agreement_events(household_id,agreement_id,kind,status,actor,created_at) select hid,agreement,'sick','done',a,clock_timestamp()+g*interval '1 millisecond' from generate_series(1,121) g;
 cursor:=null;count_rows:=0;
 loop result:=public.shared_agreements('test-gateway',case when cursor is null then 'get' else 'history' end,jsonb_build_object('actor',a,'cursor',cursor));
 if jsonb_array_length(result->'events')>50 then raise exception 'Agreement history unbounded'; end if;
 count_rows:=count_rows+jsonb_array_length(result->'events');cursor:=result->>'next_cursor';exit when cursor is null; end loop;
 if count_rows<121 then raise exception 'Agreement history lost events'; end if;

 update public.members set active=false where user_id=b;
 begin perform public.shared_home('test-gateway','get',jsonb_build_object('actor',b)); raise exception 'Former member read allowed' using errcode='P0002'; exception when raise_exception then null; end;
 begin perform public.shared_expenses('test-gateway','get',jsonb_build_object('actor',b)); raise exception 'Former member expense read allowed' using errcode='P0002'; exception when raise_exception then null; end;
 begin perform public.shared_agreements('test-gateway','history',jsonb_build_object('actor',b)); raise exception 'Former member history read allowed' using errcode='P0002'; exception when raise_exception then null; end;
 begin perform public.shared_improvements('test-gateway','search',jsonb_build_object('actor',b,'query','groceries')); raise exception 'Former member search allowed' using errcode='P0002'; exception when raise_exception then null; end;
 if exists(select 1 from jsonb_array_elements(public.shared_home('test-gateway','get','{}')->'members') m where m->>'user_id'=b::text) then raise exception 'Former member remained selectable'; end if;
end $$;
rollback;
