begin;
do $$
declare hid uuid; a uuid; b uuid; shared uuid; pid uuid; sid uuid; rid uuid; mid uuid; cid uuid; fid uuid; expense uuid:=gen_random_uuid(); result jsonb; failed boolean;
begin
  select household_id into hid from public.shared_home_config;
  select user_id into a from public.members where household_id=hid and name='Amane';
  select user_id into b from public.members where household_id=hid and name='Yuki';
  select user_id into shared from public.members where household_id=hid and name='Housemates';
  -- Token and actor enforcement for every write; read-only device can read.
  failed:=false; begin perform public.shared_household_life('wrong','get'); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Wrong token accepted'; end if;
  failed:=false; begin perform public.shared_household_life('test-gateway','pantry_save',jsonb_build_object('actor',shared,'title','Rice','status','low')); exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'Shared screen authored a staple'; end if;
  result:=public.shared_household_life('test-gateway','poll_create',jsonb_build_object('actor',a,'title','Vacuum?','options',jsonb_build_array('Yes','No'),'deadline',now()+interval '1 hour'));
  pid:=(result->'polls'->0->>'id')::uuid;
  perform public.shared_household_life('test-gateway','poll_vote',jsonb_build_object('actor',a,'id',pid,'choice',0));
  perform public.shared_household_life('test-gateway','poll_vote',jsonb_build_object('actor',a,'id',pid,'choice',1));
  if (select count(*) from public.house_poll_votes where poll_id=pid)<>1 or (select choice from public.house_poll_votes where poll_id=pid)<>1 then raise exception 'Changed vote duplicated'; end if;
  failed:=false; begin perform public.shared_household_life('test-gateway','poll_vote',jsonb_build_object('actor',a,'id',pid,'choice',2)); exception when raise_exception then failed:=true; end;
  if not failed then raise exception 'Invalid choice accepted'; end if;
  failed:=false; begin perform public.shared_household_life('test-gateway','poll_decide',jsonb_build_object('actor',a,'id',pid,'decision','Buy it')); exception when raise_exception then failed:=true; end;
  if not failed then raise exception 'Decision saved before deadline'; end if;
  update public.house_polls set deadline=now()-interval '1 second' where id=pid;
  failed:=false; begin perform public.shared_household_life('test-gateway','poll_vote',jsonb_build_object('actor',a,'id',pid,'choice',0)); exception when raise_exception then failed:=true; end;
  if not failed then raise exception 'Late vote accepted'; end if;
  perform public.shared_household_life('test-gateway','poll_decide',jsonb_build_object('actor',a,'id',pid,'decision','Keep the current vacuum'));
  failed:=false; begin perform public.shared_household_life('test-gateway','poll_decide',jsonb_build_object('actor',a,'id',pid,'decision','Overwrite')); exception when raise_exception then failed:=true; end;
  if not failed then raise exception 'Saved decision overwritten'; end if;
  result:=public.shared_household_life('test-gateway','pantry_save',jsonb_build_object('actor',a,'title','Test rice','status','low','notes','Large bag'));
  select id into sid from public.house_pantry where household_id=hid and title='Test rice';
  result:=public.shared_household_life('test-gateway','pantry_shop',jsonb_build_object('actor',a,'id',sid));
  if (result->>'added')::integer<>1 then raise exception 'Staple not queued'; end if;
  result:=public.shared_household_life('test-gateway','pantry_shop',jsonb_build_object('actor',a,'id',sid));
  if (result->>'added')::integer<>0 then raise exception 'Shopping duplicate created'; end if;
  update public.entries set done=true where household_id=hid and title='Test rice';
  result:=public.shared_household_life('test-gateway','pantry_shop',jsonb_build_object('actor',a,'id',sid));
  if (result->>'added')::integer<>1 then raise exception 'Bought staple blocked rebuy'; end if;
  perform public.shared_household_life('test-gateway','maintenance_save',jsonb_build_object('actor',a,'title','Leaky washer','description','Water underneath','assignee',b,'status','open'));
  select id into rid from public.house_maintenance where title='Leaky washer' and household_id=hid;
  failed:=false; begin perform public.shared_household_life('test-gateway','maintenance_save',jsonb_build_object('actor',a,'id',rid,'title','Leaky washer','status','resolved')); exception when raise_exception then failed:=true; end;
  if not failed then raise exception 'Repair resolved without notes'; end if;
  perform public.shared_household_life('test-gateway','photo_attach',jsonb_build_object('actor',a,'request_id',rid,'storage_path',hid::text||'/'||rid::text||'/washer.png','file_name','washer.png','content_type','image/png','size_bytes',100));
  select id into fid from public.house_maintenance_photos where request_id=rid;
  if public.shared_household_life('test-gateway','photo',jsonb_build_object('id',fid))->'photo'->>'file_name'<>'washer.png' then raise exception 'Photo not readable'; end if;
  perform public.shared_household_life('test-gateway','maintenance_save',jsonb_build_object('actor',a,'id',rid,'title','Leaky washer','assignee',b,'status','resolved','resolution','Replaced hose'));
  if not exists(select 1 from public.house_maintenance where id=rid and resolved_at is not null and resolution='Replaced hose') then raise exception 'Resolution not saved'; end if;
  perform public.shared_household_life('test-gateway','maintenance_save',jsonb_build_object('actor',a,'id',rid,'title','Leaky washer','status','in_progress','resolution','Leak returned'));
  if exists(select 1 from public.house_maintenance where id=rid and resolved_at is not null) then raise exception 'Reopened repair kept resolved timestamp'; end if;
  result:=public.shared_household_life('test-gateway','maintenance_delete',jsonb_build_object('actor',a,'id',rid));
  if jsonb_array_length(result->'paths')<>1 or exists(select 1 from public.house_maintenance_photos where id=fid) then raise exception 'Repair deletion left photos'; end if;
  perform public.shared_household_life('test-gateway','meal_save',jsonb_build_object('actor',a,'title','Test dinner','date','2026-09-20','cook',b,'ingredients',jsonb_build_array(jsonb_build_object('title','Test rice','missing',true),jsonb_build_object('title','Test beans','missing',true),jsonb_build_object('title','Oil','missing',false))));
  select id,calendar_entry_id into mid,cid from public.house_meals where title='Test dinner' and household_id=hid;
  if cid is null or not exists(select 1 from public.entries where id=cid and kind='event' and category='Together') then raise exception 'Dinner missing calendar link'; end if;
  result:=public.shared_household_life('test-gateway','meal_shop',jsonb_build_object('actor',a,'id',mid));
  if (result->>'added')::integer<>1 then raise exception 'Meal did not deduplicate missing ingredients'; end if;
  perform public.shared_household_life('test-gateway','meal_save',jsonb_build_object('actor',a,'id',mid,'title','Updated dinner','date','2026-09-21','ingredients',jsonb_build_array(jsonb_build_object('title','Test beans','missing',false))));
  if (select ingredients->0->>'missing' from public.house_meals where id=mid)<>'false' or (select date from public.entries where id=cid)<>'2026-09-21'::date then raise exception 'Meal edit did not update ingredients and calendar'; end if;
  perform public.shared_household_life('test-gateway','meal_delete',jsonb_build_object('actor',a,'id',mid));
  if exists(select 1 from public.entries where id=cid) then raise exception 'Meal deletion left calendar plan'; end if;
  perform public.shared_expenses('test-gateway','create',jsonb_build_object('actor',a,'id',expense,'kind','expense','title','Budget groceries','date','2026-09-16','amount_cents',1000,'paid_by',a,'shares',jsonb_build_object(a::text,1000)));
  perform public.shared_household_life('test-gateway','budget_target',jsonb_build_object('actor',a,'month','2026-09-01','category','groceries','target_cents',25000));
  perform public.shared_household_life('test-gateway','budget_category',jsonb_build_object('actor',a,'id',expense,'category','groceries'));
  perform public.shared_household_life('test-gateway','budget_category',jsonb_build_object('actor',a,'id',expense,'category','utilities'));
  if (select category from public.house_budget_expenses where expense_id=expense)<>'utilities' then raise exception 'Category not updated'; end if;
  perform public.shared_expenses('test-gateway','delete',jsonb_build_object('actor',a,'id',expense));
  if exists(select 1 from public.house_budget_expenses where expense_id=expense) then raise exception 'Deleted expense left classification'; end if;
  -- A second household and valid member cannot read or write this household's records.
  insert into auth.users(id) values(gen_random_uuid()) returning id into b;
  insert into public.households(name,owner_id) values('Other house',b) returning id into cid;
  insert into public.members(user_id,household_id,name) values(b,cid,'Other person');
  update public.shared_home_config set household_id=cid,gateway_hash=encode(extensions.digest('other-life-gateway','sha256'),'hex');
  if jsonb_array_length(public.shared_household_life('other-life-gateway','get')->'pantry')<>0 then raise exception 'Cross-household read'; end if;
  failed:=false; begin perform public.shared_household_life('other-life-gateway','pantry_shop',jsonb_build_object('actor',b,'id',sid)); exception when raise_exception then failed:=true; end;
  if not failed then raise exception 'Cross-household pantry write'; end if;
  failed:=false; begin perform public.shared_household_life('other-life-gateway','poll_vote',jsonb_build_object('actor',b,'id',pid,'choice',0)); exception when raise_exception then failed:=true; end;
  if not failed then raise exception 'Cross-household vote'; end if;
end $$;
rollback;
