begin;
do $$
declare hid uuid; a uuid; b uuid; bill uuid; chore uuid; request uuid; sid uuid; stamp timestamptz; result jsonb; token uuid:=gen_random_uuid(); write_id uuid:=gen_random_uuid(); blocked boolean; eid uuid;
begin
 select household_id into hid from public.shared_home_config;
 select owner_id into a from public.households where id=hid;
 select user_id into b from public.members where household_id=hid and user_id<>a and name<>'Housemates' and active;
 result:=public.shared_home('test-gateway','create',jsonb_build_object('actor',a,'kind','event','title','Uneven rent','category','Rent','amount',100.01,'date',current_date,'repeat','monthly','repeat_until',current_date+70,'bill_shares',jsonb_build_object(a,7000,b,3001)));
 bill:=(result->'entries'->0->>'id')::uuid;sid:=(result->'entries'->0->>'series_id')::uuid;
 if (select count(*) from public.entries where series_id=sid and bill_shares=jsonb_build_object(a,7000,b,3001))<2 then raise exception 'Recurring shares not retained'; end if;
 result:=public.shared_home('test-gateway','update',jsonb_build_object('actor',a,'id',bill,'scope','series','amount',100.01,'bill_shares',jsonb_build_object(a,6000,b,4001),'undo_token',token));
 if exists(select 1 from public.entries where series_id=sid and bill_shares<>jsonb_build_object(a,6000,b,4001)) then raise exception 'Series split not updated'; end if;
 perform public.shared_home('test-gateway','undo_edit',jsonb_build_object('actor',a,'undo_token',token));
 if exists(select 1 from public.entries where series_id=sid and bill_shares<>jsonb_build_object(a,7000,b,3001)) then raise exception 'Split undo failed'; end if;
 token:=gen_random_uuid();
 perform public.shared_home('test-gateway','delete',jsonb_build_object('actor',a,'id',bill,'undo_token',token));
 perform public.shared_home('test-gateway','restore',jsonb_build_object('actor',a,'undo_token',token));
 if (select bill_shares from public.entries where id=bill) is distinct from jsonb_build_object(a,7000,b,3001) then raise exception 'Delete undo lost shares'; end if;
 result:=public.shared_home('test-gateway','payment',jsonb_build_object('actor',a,'id',bill,'cover',true));
 if (result->'expense'->>'amount_cents')::integer<>10001 or result->'expense'->'shares'<>jsonb_build_object(a,7000,b,3001) then raise exception 'Cover ignored custom shares'; end if;
 eid:=(result->'expense'->>'id')::uuid;
 blocked:=false;
 begin perform public.shared_home('test-gateway','update',jsonb_build_object('actor',a,'id',bill,'bill_shares',jsonb_build_object(a,5000,b,5001))); exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Linked bill split edited'; end if;
 perform public.shared_expenses('test-gateway','delete',jsonb_build_object('actor',a,'id',eid));
 result:=public.shared_home('test-gateway','payment',jsonb_build_object('actor',b,'id',bill,'log_share',true));
 if (result->'expense'->>'amount_cents')::integer<>3001 or result->'expense'->'shares'<>jsonb_build_object(b,3001) then raise exception 'Log share ignored custom split'; end if;
 blocked:=false;
 begin
  perform public.shared_home('test-gateway','create',jsonb_build_object('actor',a,'kind','event','title','Invalid split','category','Bill','date',current_date,'amount',1,'bill_shares',jsonb_build_object(a,40,b,40)));
  set constraints validate_bill_shares immediate;
 exception when raise_exception then blocked:=true;
 end;
 if not blocked then raise exception 'Invalid total accepted'; end if;
 set constraints validate_bill_shares deferred;
 result:=public.shared_home('test-gateway','create',jsonb_build_object('actor',a,'kind','task','title','Ancient vacuum','category','Chore','date',current_date-300));
 chore:=(result->'entries'->0->>'id')::uuid;
 perform public.shared_home('test-gateway','update',jsonb_build_object('actor',b,'id',chore,'done',true));
 select last_done_at into stamp from public.entries where id=chore and last_done_by=b;
 if stamp is null then raise exception 'Actual chore time/actor missing'; end if;
 perform public.shared_home('test-gateway','update',jsonb_build_object('actor',a,'id',chore,'done',false));
 if (select last_done_at from public.entries where id=chore) is distinct from stamp then raise exception 'Reopen erased last done'; end if;
 -- Last-done history for a series can live outside the board's date window.
 update public.entries set series_id=gen_random_uuid() where id=chore returning series_id into sid;
 result:=public.shared_home('test-gateway','create',jsonb_build_object('actor',a,'kind','task','title','Vacuum next turn','category','Chore','date',current_date));
 update public.entries set series_id=sid where id=(result->'entries'->0->>'id')::uuid;
 result:=public.shared_home('test-gateway','get');
 if not exists(select 1 from jsonb_array_elements(result->'entries') e where e->>'title'='Vacuum next turn' and (e->>'last_done_by')::uuid=b and (e->>'last_done_at')::timestamptz=stamp) then raise exception 'Series history outside board missing'; end if;
 result:=public.shared_search('test-gateway','search',jsonb_build_object('query','ancient vacuum'));
 if jsonb_array_length(result->'results')<>1 then raise exception 'Search missed old chores'; end if;
 perform public.shared_handbook('test-gateway','create',jsonb_build_object('actor',a,'section','other','title','Café reference','value','Blue kettle secret','notes','Manual on the shelf'));
 result:=public.shared_search('test-gateway','search',jsonb_build_object('query','cafe kettle'));
 if jsonb_array_length(result->'results')<>1 or result->'results'->0->>'tab'<>'House handbook' then raise exception 'Accent/value search failed'; end if;
 blocked:=false;
 begin perform public.shared_search('wrong','search',jsonb_build_object('query','rent')); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'Search gateway leaked'; end if;
 result:=public.shared_home('test-gateway','create',jsonb_build_object('actor',a,'kind','request','title','Offline milk','category','Need','amount',2.01));
 request:=(result->'entries'->0->>'id')::uuid;
 result:=public.shared_shopping('test-gateway','sync',jsonb_build_object('actor',a,'household_id',hid,'id',request,'write_id',write_id,'done',true,'expected_done',false,'expected_title','Offline milk','expected_category','Need','expected_amount',2.01));
 if result->>'ok'<>'true' or not (select done from public.entries where id=request) or not exists(select 1 from public.household_expenses where id=request and amount_cents=201) then raise exception 'Offline purchase not atomic'; end if;
 result:=public.shared_shopping('test-gateway','sync',jsonb_build_object('actor',a,'household_id',hid,'id',request,'write_id',write_id,'done',true,'expected_done',false));
 if result->>'ok'<>'true' or (select count(*) from public.household_expenses where id=request)<>1 then raise exception 'Retry duplicated purchase'; end if;
 result:=public.shared_shopping('test-gateway','sync',jsonb_build_object('actor',b,'household_id',hid,'id',request,'write_id',gen_random_uuid(),'done',true,'expected_done',false,'expected_title','Offline milk','expected_category','Need','expected_amount',2.01));
 if result->>'conflict'<>'true' then raise exception 'Concurrent shopping overwritten'; end if;
 blocked:=false;
 begin perform public.shared_shopping('test-gateway','sync',jsonb_build_object('actor',a,'household_id',gen_random_uuid(),'id',request,'write_id',gen_random_uuid(),'done',false,'expected_done',true)); exception when raise_exception then blocked:=true; end;
 if not blocked then raise exception 'Shopping household mismatch allowed'; end if;
 -- Search must paginate rather than silently hide excess matches.
 insert into public.entries(household_id,created_by,kind,title,category) select hid,a,'note','Pagination probe '||n,'Note' from generate_series(1,55) n;
 result:=public.shared_search('test-gateway','search',jsonb_build_object('query','pagination probe'));
 if jsonb_array_length(result->'results')<>50 or result->>'next_offset'<>'50' then raise exception 'Search pagination missing'; end if;
 result:=public.shared_search('test-gateway','search',jsonb_build_object('query','pagination probe','offset',50));
 if jsonb_array_length(result->'results')<>5 or result->>'next_offset' is not null then raise exception 'Search final page wrong'; end if;
 if has_function_privilege('anon','public.shared_home_before_search_offline(text,text,jsonb)','execute') then raise exception 'Legacy bypass exposed'; end if;
 set constraints all immediate;
end $$;
rollback;
